spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fyp-grading
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
