build:
  version: ${BUILD_VERSION}

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "FYP Grading project - Admin Microservice"
    version: ${BUILD_VERSION}

logging:
  level:
    root: INFO

services:
  evaluation-service-name: ${EVALUATION_SERVICE_NAME}
  notification-service-name: ${NOTIFICATION_SERVICE_NAME}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # this will in fact not be used as the service will register with eureka
  # and get its configuration from the config server dynamically in the bootstrap phase (bootstrap.yml)
  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true # config server reached via Eureka
      name: config

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${PORT}
