version: '3.7'
services:
  admin-service:
    build:
      context: ../../..
    container_name: admin-service
    image: admin-service
    ports:
      - '8080:8080'
    networks:
      - fyp-grading

  rabbitmq:
    build:
      context: rabbitmq
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - fyp-grading

  postgres:
    build:
      context: postgres
    ports:
      - '5432:5432'
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: fyp-grading
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
        - fyp-grading

networks:
  fyp-grading:
    driver: bridge